name: Action Test

on: 
  workflow_dispatch:
    inputs:
      unk:
        description: 'stub input'
        required: false
        default: false


jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Test foreground
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
        foreground: false
    - name: Test foreground
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
        foreground: false